### PR TITLE
support Get#setClosestRowBefore method

### PR DESCRIPTION
**Pull request by TanUkkii007**
This PR adds setClosestRowBefore method to Get request, which is supported since HBase 0.96.

### CODE REVIEW

**Comment by TanUkkii007** [comment]
I checked integration test locally for HBase 1.2.2.

**Comment by elliottneilclark** [comment]
setClosestRowBefore is being actively removed in HBase. Probably better to just support reverse scanning.

**Comment by TanUkkii007** [comment]
Thanks. I found setClosestRowBefore would be deprecated in HBase 2.0.0.
I can use reverse scan instead.
It seems reverse scan will be supported in v1.8.0 #122 . 
I cannot find 1.8.0-SNAPSHOT jar, though.
Is there any plan to release 1.8.0?

**Comment by manolama** [comment]
@TanUkkii007 Yeah, I have a few more bits to add to 1.8 but you should find Snapshots in Sonatype's repo now: https://oss.sonatype.org/content/repositories/snapshots/org/hbase/asynchbase/1.8.0-SNAPSHOT/

**Comment by TanUkkii007** [comment]
Nice! I will use snapshot for now and be looking forward to stable release.

**Pull request closed without merging**
