### PR TITLE
Secure rpc96

### PR DESCRIPTION
**Pull request by francisliu**
This is an amended patch of pull #71 which now supports 0.96 as well.

This patch add support for security enabled 0.94. It currently has only one mechanism: kerberos. So this can't be used in MapReduce jobs or the like. We've internally been using a hacky implementation of this patch as part of opentsdb and have had no issues so far. 

Most of the logic is in SecurityHelper which does the handshaking, wrapping, etc.

There were some configs that needed to be set. Since we don't have a config object everything is passed via properties:

```
[org.hbase.async.security.94]
hbase.security.authentication=<MECHANISM>
hbase.kerberos.regionserver.principal=<REGIONSERVER PRINCIPAL>
hbase.rpc.protection=[authentication|integrity|privacy]
hbase.sasl.clientconfig=<JAAS Profile Name>
java.security.auth.login.config=<Path to JAAS conf>
```

Basic properties that need to be set are:

```
[-Dorg.hbase.async.security.94] -Dhbase.security.authentication=kerberos
-Dhbase.kerberos.regionserver.principal=hbase/_HOST@MYREALM.COM
-Dhbase.sasl.clientconfig=Client -Djava.security.auth.login.config=/path/to/jaas.conf
```

A JAAS profile looks like this:

For non-headless (ie using kinit):

```
Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=false
  useTicketCache=true;
};
```

For headless users or services:

```
Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  useTicketCache=false
  keyTab="/path/to/hbase.keytab"
  principal="hbase/rs1.host.com@MYREALM.COM";
};
```

Note the value passed in `hbase.sasl.clientconfig` should match the profile name defined in the jaas conf.

### CODE REVIEW

**Comment by kkossack** [comment]
Is it still in the plan for 1.7?  Do you have a time frame for this?

**Comment by manolama** [comment]
Yeah, still in the plan. I've been cleaning and unit testing it. Hopefully by this weekend.

**Comment by tsuna** [comment]
@jbnote wow that's really cool :)

**Comment by kkossack** [comment]
Excellent news! Is any of your testing with openTSDB?

**Comment by shalonwood** [comment]
Is this still going to be merged for the 1.7 release? There doesn't seem to have been any activity on this issue since November, and lack of Kerberos is causing issues for one of our teams. If there's a reason it's not going to be merged (e.g. causes instability for some as-yet undetermined reason) I don't want to suggest they apply it themselves, though.

**Comment by andysabo** [comment]
What date do we expect for the 1.7 release?  Thanks.

**Comment by manolama** [comment]
Merged in 2a0d381c5f288d34696b06a67b1582a57977f23b

@shalonwood, @andysabo  please give it a try and let me know if it works out for you guys. I'm aiming for a 1.7 RC release by HbaseCon in May. Thanks!

**Pull request closed without merging**
